### ISSUE TITLE
Bug: You can submit a new todo with a null date. Breaking the database/application.

### ISSUE THREAD

**Issue by ApplePieAngel** [CodingWithDan/Nothing-but-Notes#10]
If you don't click a date, it'll create a dueDate value for the todo object in your database with a null value. You'd have to delete it from the database/clear it or else whenever do a GET request for the page it'll run getToDo and break as its accessing a null value for a mandatory value in the schema due to 'Todo validation failed'.

**Comment by ApplePieAngel** [comment]
Possible fixes include making the form duedate mandatory. As well as having failsafe's incase null data gets accessed from the database. 

Probably should prevent name from being null as well.

**Comment by ApplePieAngel** [comment]
As well as having failsafe's incase null data gets accessed from the database.

**Comment by codEno12** [comment]
Fixed it! 
Added a required attribute to the input elements in our todos.ejs file!
