### ISSUE TITLE
Bold, italicize, strikethrough feature

### ISSUE THREAD

**Issue by CodingWithDan** [CodingWithDan/Nothing-but-Notes#2]
We need add a way to spice up the text. I think we should at the very least try to implement: 

- Bold
- Italicize 
- Strikethrough

Anything else is gravy!

**Comment by CodingWithDan** [comment]
Assigning myself this, as well as making the text box into a text area

**Comment by ApplePieAngel** [comment]
These features have currently been implemented. I'll be closing this issue.
